// Product data source for all product pages
export const productData = [
  // Gameforge West Servers
  { name: 'Metin2 Eostre Won', handle: 'metin2-eostre-won', price: 1.20, category: 'Gameforge West', logo: '/products/eostre.png' },
  { name: 'Metin2 Teutonia Won', handle: 'metin2-teutonia-won', price: 0.37, category: 'Gameforge West', logo: '/products/teutonia.png' },
  { name: 'Metin2 Germania Won', handle: 'metin2-germania-won', price: 0.37, category: 'Gameforge West', logo: '/products/germania.png' },
  { name: 'Metin2 Europe Won', handle: 'metin2-europe-won', price: 0.6, category: 'Gameforge West', logo: '/products/europa.png' },
  { name: 'Metin2 Tigerghost Won', handle: 'metin2-tigerghost-won', price: 0.95, category: 'Gameforge West', logo: '/products/tigerghost.png' },
  { name: 'Metin2 Ruby Chimera Won', handle: 'metin2-ruby-chimera-won', price: 0.7, category: 'Gameforge West', logo: '/products/ruby_chimera.png' },
  { name: 'Metin2 Emerald Aurora Won', handle: 'metin2-emerald-aurora-won', price: 0.63, category: 'Gameforge West', logo: '/products/emerald.png' },
  { name: 'Metin2 Iberia Won', handle: 'metin2-iberia-won', price: 0.37, category: 'Gameforge West', logo: '/products/iberia.png' },
  { name: 'Metin2 Italy Won', handle: 'metin2-italy-won', price: 0.37, category: 'Gameforge West', logo: '/products/italy.png' },
  { name: 'Metin2 Azrael Won', handle: 'metin2-azrael-won', price: 0.24, category: 'Gameforge West', logo: '/products/azrael.png' },
  { name: 'Metin2 Onyx Obsidian Won', handle: 'metin2-onyx-obsidian-won', price: 0.75, category: 'Gameforge West', logo: '/products/onyx.png' },
  // Gameforge East Servers
  { name: 'Metin2 Willow Won', handle: 'metin2-willow-won', price: 2.25, category: 'Gameforge East' },
  { name: 'Metin2 Ruby Kirin Won', handle: 'metin2-ruby-kirin-won', price: 0.5, category: 'Gameforge East' },
  { name: 'Metin2 Cesko Won', handle: 'metin2-cesko-won', price: 0.45, category: 'Gameforge East' },
  { name: 'Metin2 Magyarorszag Won', handle: 'metin2-magyarorszag-won', price: 0.37, category: 'Gameforge East' },
  { name: 'Metin2 Polska Won', handle: 'metin2-polska-won', price: 0.4, category: 'Gameforge East' },
  { name: 'Metin2 Romania Won', handle: 'metin2-romania-won', price: 0.5, category: 'Gameforge East' },
  { name: 'Metin2 Tara Romanesca Won', handle: 'metin2-tara-romanesca-won', price: 0.5, category: 'Gameforge East' },
  { name: 'Metin2 Greece Won', handle: 'metin2-greece-won', price: 0.65, category: 'Gameforge East' },
  { name: 'Metin2 Arabia Won', handle: 'metin2-arabia-won', price: 0.75, category: 'Gameforge East' },
  // Gameforge TR Servers
  { name: 'Metin2 Zephyr Won', handle: 'metin2-zephyr-won', price: 0.7, category: 'Gameforge TR' },
  { name: 'Metin2 Ruby Lucifer Won', handle: 'metin2-ruby-lucifer-won', price: 0.23, category: 'Gameforge TR' },
  { name: 'Metin2 Onyx Bazalt Won', handle: 'metin2-onyx-bazalt-won', price: 0.33, category: 'Gameforge TR' },
  { name: 'Metin2 Emerald Alesta Won', handle: 'metin2-emerald-alesta-won', price: 0.32, category: 'Gameforge TR' },
  { name: 'Metin2 Ruby Charon Won', handle: 'metin2-ruby-charon-won', price: 0.2, category: 'Gameforge TR' },
  { name: 'Metin2 Anadolu Won', handle: 'metin2-anadolu-won', price: 0.55, category: 'Gameforge TR' },
  { name: 'Metin2 Arkadaslar Won', handle: 'metin2-arkadaslar-won', price: 0.25, category: 'Gameforge TR' },
  { name: 'Metin2 Bagjanamu Won', handle: 'metin2-bagjanamu-won', price: 0.24, category: 'Gameforge TR' },
  { name: 'Metin2 Barbaros Won', handle: 'metin2-barbaros-won', price: 0.33, category: 'Gameforge TR' },
  { name: 'Metin2 Dandanakan Won', handle: 'metin2-dandanakan-won', price: 0.25, category: 'Gameforge TR' },
  { name: 'Metin2 Ezel Won', handle: 'metin2-ezel-won', price: 0.36, category: 'Gameforge TR' },
  // Private Servers (fixed price 10€)
  { name: 'Alturi2 Yang 18KKK', handle: 'alturi2-yang-18kkk', price: 10, category: 'Private Servers' },
  { name: 'Elveron Yang 12KKK', handle: 'elveron-yang-12kkk', price: 10, category: 'Private Servers', logo: '/products/elveron.png' },
  { name: 'Kerion Yang 1KKKK', handle: 'kerion-yang-1kkkk', price: 10, category: 'Private Servers' },
  { name: 'NewMt2 Yang 17KKK', handle: 'newmt2-yang-17kkk', price: 10, category: 'Private Servers' },
  { name: 'Solis2 Yang 750KKK', handle: 'solis2-yang-750kkk', price: 10, category: 'Private Servers' },
  { name: 'Rubinum Saphirus Yang 300KKK', handle: 'rubinum-saphirus-yang-300kkk', price: 10, category: 'Private Servers' },
  { name: 'Merlis Yang 27KKK', handle: 'merlis-yang-27kkk', price: 10, category: 'Private Servers' },
  { name: 'Lucerna Laetus Yang 300KKK', handle: 'lucerna-laetus-yang-300kkk', price: 10, category: 'Private Servers' },
  { name: 'Levia Yang 30KKK', handle: 'levia-yang-30kkk', price: 10, category: 'Private Servers' },
  { name: 'Celestial World 1.2KK', handle: 'celestial-world-12kk', price: 10, category: 'Private Servers' },
  { name: 'Notorius2 Yang 350KKK', handle: 'notorius2-yang-350kkk', price: 10, category: 'Private Servers' },
  { name: 'Pegasus2 Yang', handle: 'pegasus2-yang', price: 10, category: 'Private Servers' },
  { name: 'Fortis2 Yang 170KKK', handle: 'fortis2-yang-170kkk', price: 10, category: 'Private Servers' },
  { name: 'Helios2 Yang 25KKK', handle: 'helios2-yang-25kkk', price: 10, category: 'Private Servers' },
  { name: 'M2Classic Yang 800KK', handle: 'm2classic-yang-800kk', price: 10, category: 'Private Servers' },
  { name: 'Shiva Yang 800KK', handle: 'shiva-yang-800kk', price: 10, category: 'Private Servers' },
  { name: 'Azyrah 1500 Won', handle: 'azyrah-1500-won', price: 10, category: 'Private Servers' },
  { name: 'Rubinum 300KKK', handle: 'rubinum-300kkk', price: 10, category: 'Private Servers' },
  { name: 'Zenit 120KKK', handle: 'zenit-120kkk', price: 10, category: 'Private Servers' },
  // Mobile Metin2 (fixed price 10€)
  { name: 'Royale Yang', handle: 'royale-yang', price: 10, category: 'Mobile Metin2' },
  { name: 'Mobile2 Tuva Yang 20KK', handle: 'mobile2-tuva-yang-20kk', price: 10, category: 'Mobile Metin2' },
  { name: 'Mobile2 Tramola Yang 12KK', handle: 'mobile2-tramola-yang-12kk', price: 10, category: 'Mobile Metin2' },
  { name: 'Mobile2 Alesta Yang 30KK', handle: 'mobile2-alesta-yang-30kk', price: 10, category: 'Mobile Metin2' },
]; 