// Product data source for all product pages
export const productData = [
  // Gameforge West Servers
  { name: 'Metin2 Eostre Won', price: 1.20, category: 'Gameforge West', logo: '/products/eostre.png' },
  { name: 'Metin2 Teutonia Won', price: 0.37, category: 'Gameforge West', logo: '/products/teutonia.png' },
  { name: 'Metin2 Germania Won', price: 0.37, category: 'Gameforge West', logo: '/products/germania.png' },
  { name: 'Metin2 Europe Won', price: 0.6, category: 'Gameforge West', logo: '/products/europa.png' },
  { name: 'Metin2 Tigerghost Won', price: 0.95, category: 'Gameforge West', logo: '/products/tigerghost.png' },
  { name: 'Metin2 Ruby Chimera Won', price: 0.7, category: 'Gameforge West', logo: '/products/ruby_chimera.png' },
  { name: 'Metin2 Emerald Aurora Won', price: 0.63, category: 'Gameforge West', logo: '/products/emerald.png' },
  { name: 'Metin2 Iberia Won', price: 0.37, category: 'Gameforge West', logo: '/products/iberia.png' },
  { name: 'Metin2 Italy Won', price: 0.37, category: 'Gameforge West', logo: '/products/italy.png' },
  { name: 'Metin2 Azrael Won', price: 0.24, category: 'Gameforge West', logo: '/products/azrael.png' },
  { name: 'Metin2 Onyx Obsidian Won', price: 0.75, category: 'Gameforge West' },
  // Gameforge East Servers
  { name: 'Metin2 Willow Won', price: 2.25, category: 'Gameforge East' },
  { name: 'Metin2 Ruby Kirin Won', price: 0.5, category: 'Gameforge East' },
  { name: 'Metin2 Cesko Won', price: 0.45, category: 'Gameforge East' },
  { name: 'Metin2 Magyarorszag Won', price: 0.37, category: 'Gameforge East' },
  { name: 'Metin2 Polska Won', price: 0.4, category: 'Gameforge East' },
  { name: 'Metin2 Romania Won', price: 0.5, category: 'Gameforge East' },
  { name: 'Metin2 Tara Romanesca Won', price: 0.5, category: 'Gameforge East' },
  { name: 'Metin2 Greece Won', price: 0.65, category: 'Gameforge East' },
  { name: 'Metin2 Arabia Won', price: 0.75, category: 'Gameforge East' },
  // Gameforge TR Servers
  { name: 'Metin2 Zephyr Won', price: 0.7, category: 'Gameforge TR' },
  { name: 'Metin2 Ruby Lucifer Won', price: 0.23, category: 'Gameforge TR' },
  { name: 'Metin2 Onyx Bazalt Won', price: 0.33, category: 'Gameforge TR' },
  { name: 'Metin2 Emerald Alesta Won', price: 0.32, category: 'Gameforge TR' },
  { name: 'Metin2 Ruby Charon Won', price: 0.2, category: 'Gameforge TR' },
  { name: 'Metin2 Anadolu Won', price: 0.55, category: 'Gameforge TR' },
  { name: 'Metin2 Arkadaslar Won', price: 0.25, category: 'Gameforge TR' },
  { name: 'Metin2 Bagjanamu Won', price: 0.24, category: 'Gameforge TR' },
  { name: 'Metin2 Barbaros Won', price: 0.33, category: 'Gameforge TR' },
  { name: 'Metin2 Dandanakan Won', price: 0.25, category: 'Gameforge TR' },
  { name: 'Metin2 Ezel Won', price: 0.36, category: 'Gameforge TR' },
  // Private Servers (fixed price 10€)
  { name: 'Alturi2 Yang 18KKK', price: 10, category: 'Private Servers' },
  { name: 'Elveron Yang 12KKK', price: 10, category: 'Private Servers', logo: '/products/elveron.png' },
  { name: 'Kerion Yang 1KKKK', price: 10, category: 'Private Servers' },
  { name: 'NewMt2 Yang 17KKK', price: 10, category: 'Private Servers' },
  { name: 'Solis2 Yang 750KKK', price: 10, category: 'Private Servers' },
  { name: 'Rubinum Saphirus Yang 300KKK', price: 10, category: 'Private Servers' },
  { name: 'Merlis Yang 27KKK', price: 10, category: 'Private Servers' },
  { name: 'Lucerna Laetus Yang 300KKK', price: 10, category: 'Private Servers' },
  { name: 'Levia Yang 30KKK', price: 10, category: 'Private Servers' },
  { name: 'Celestial World 1.2KK', price: 10, category: 'Private Servers' },
  { name: 'Notorius2 Yang 350KKK', price: 10, category: 'Private Servers' },
  { name: 'Pegasus2 Yang', price: 10, category: 'Private Servers' },
  { name: 'Fortis2 Yang 170KKK', price: 10, category: 'Private Servers' },
  { name: 'Helios2 Yang 25KKK', price: 10, category: 'Private Servers' },
  { name: 'M2Classic Yang 800KK', price: 10, category: 'Private Servers' },
  { name: 'Shiva Yang 800KK', price: 10, category: 'Private Servers' },
  { name: 'Azyrah 1500 Won', price: 10, category: 'Private Servers' },
  { name: 'Rubinum 300KKK', price: 10, category: 'Private Servers' },
  { name: 'Zenit 120KKK', price: 10, category: 'Private Servers' },
  // Mobile Metin2 (fixed price 10€)
  { name: 'Royale Yang', price: 10, category: 'Mobile Metin2' },
  { name: 'Mobile2 Tuva Yang 20KK', price: 10, category: 'Mobile Metin2' },
  { name: 'Mobile2 Tramola Yang 12KK', price: 10, category: 'Mobile Metin2' },
  { name: 'Mobile2 Alesta Yang 30KK', price: 10, category: 'Mobile Metin2' },
]; 